### ISSUE TITLE
[Bug] ValueError: COVIDx: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by Xglbrilliant** [open-mmlab/mmclassification#1186] opened 2022-11-10 08:51 UTC
### 分支

master 分支 (0.24 或其他 0.x 版本)

### 描述该错误

When I use densenet to perform a classification experiment on a medical image dataset, an error occurs.
code error message：
```
Traceback (most recent call last):
  File "tools/train.py", line 205, in <module>
    main()
  File "tools/train.py", line 178, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/s316/Workspace/xionggl/mmclassification/mmcls/datasets/builder.py", line 55, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/s316/.conda/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
ValueError: COVIDx: too many values to unpack (expected 2)
```
run command：
```
python tools/train.py configs/densenet/densenet121_1×b64_COVIDx.py \
	--work-dir work_dirs/densenet/densenet121_1×b64_COVIDx/
```

### 环境信息

{'sys.platform': 'linux',
 'Python': '3.8.13 (default, Oct 21 2022, 23:50:54) [GCC 11.2.0]',
 'CUDA available': True,
 'GPU 0': 'NVIDIA GeForce RTX 2080 Ti',
 'CUDA_HOME': '/usr/local/cuda',
 'NVCC': 'Cuda compilation tools, release 11.3, V11.3.58',
 'GCC': 'gcc (Ubuntu 7.5.0-6ubuntu2) 7.5.0',
 'PyTorch': '1.12.0',
 'PyTorch compiling details': 'PyTorch built with:\n'
                              '  - GCC 9.3\n'
                              '  - C++ Version: 201402\n'
                              '  - Intel(R) oneAPI Math Kernel Library Version '
                              '2021.4-Product Build 20210904 for Intel(R) 64 '
                              'architecture applications\n'
                              '  - Intel(R) MKL-DNN v2.6.0 (Git Hash '
                              '52b5f107dd9cf10910aaa19cb47f3abf9b349815)\n'
                              '  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n'
                              '  - LAPACK is enabled (usually provided by '
                              'MKL)\n'
                              '  - NNPACK is enabled\n'
                              '  - CPU capability usage: AVX2\n'
                              '  - CUDA Runtime 11.3\n'
                              '  - NVCC architecture flags: '
                              '-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37\n'
                              '  - CuDNN 8.3.2  (built against CUDA 11.5)\n'
                              '  - Magma 2.5.2\n'
                              '  - Build settings: BLAS_INFO=mkl, '
                              'BUILD_TYPE=Release, CUDA_VERSION=11.3, '
                              'CUDNN_VERSION=8.3.2, '
                              'CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, '
                              'CXX_FLAGS= -Wno-deprecated '
                              '-fvisibility-inlines-hidden -DUSE_PTHREADPOOL '
                              '-fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM '
                              '-DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK '
                              '-DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE '
                              '-DEDGE_PROFILER_USE_KINETO -O2 -fPIC '
                              '-Wno-narrowing -Wall -Wextra '
                              '-Werror=return-type '
                              '-Wno-missing-field-initializers '
                              '-Wno-type-limits -Wno-array-bounds '
                              '-Wno-unknown-pragmas -Wno-unused-parameter '
                              '-Wno-unused-function -Wno-unused-result '
                              '-Wno-unused-local-typedefs -Wno-strict-overflow '
                              '-Wno-strict-aliasing '
                              '-Wno-error=deprecated-declarations '
                              '-Wno-stringop-overflow -Wno-psabi '
                              '-Wno-error=pedantic -Wno-error=redundant-decls '
                              '-Wno-error=old-style-cast '
                              '-fdiagnostics-color=always -faligned-new '
                              '-Wno-unused-but-set-variable '
                              '-Wno-maybe-uninitialized -fno-math-errno '
                              '-fno-trapping-math -Werror=format '
                              '-Werror=cast-function-type '
                              '-Wno-stringop-overflow, LAPACK_INFO=mkl, '
                              'PERF_WITH_AVX=1, PERF_WITH_AVX2=1, '
                              'PERF_WITH_AVX512=1, TORCH_VERSION=1.12.0, '
                              'USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, '
                              'USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, '
                              'USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, '
                              'USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, \n',
 'TorchVision': '0.13.0',
 'OpenCV': '4.6.0',
 'MMCV': '1.7.0',
 'MMCV Compiler': 'n/a',
 'MMCV CUDA Compiler': 'n/a',
 'MMClassification': '0.24.1+'}

### 其他信息

Changes: ①Added the COVIDx_bs64.py file under the configs/_base_/datasets/ folder. ②Added the densenet121_COVIDx.py file under the configs/_base_/models/densenet/ folder. ③ Added the configuration file densenet121_1×b64_COVIDx.py under configs/densenet/. ④Configure the medical image dataset COVIDx (__init__.py file and added COVIDx.py file) under mmcls/datasets/.
The changed code is as follows:
```
# COVIDx_bs64.py
dataset_type = 'COVIDx'
img_norm_cfg = dict(
    mean=[128.928, 128.928, 128.928], std=[64.26, 64.26, 64.26], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='RandomResizedCrop', size=224),
    dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', size=(256, -1)),
    dict(type='CenterCrop', crop_size=224),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='Collect', keys=['img'])
]
data = dict(
    samples_per_gpu=64,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        data_prefix='/home/s316/Workspace/xionggl/Experiment/first/data/covid19/train',
        ann_file='/home/s316/Workspace/xionggl/Experiment/first/data/covid19/meta/train.txt',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        data_prefix='/home/s316/Workspace/xionggl/Experiment/first/data/covid19/val',
        ann_file='/home/s316/Workspace/xionggl/Experiment/first/data/covid19/meta/val.txt',
        pipeline=test_pipeline),
    test=dict(
        # replace `data/val` with `data/test` for standard test
        type=dataset_type,
        data_prefix='/home/s316/Workspace/xionggl/Experiment/first/data/covid19/test',
        ann_file='/home/s316/Workspace/xionggl/Experiment/first/data/covid19/meta/test.txt',
        pipeline=test_pipeline))
evaluation = dict(interval=1, metric='accuracy')
```
```
# densenet121_COVIDx.py
model = dict(
    type='ImageClassifier',
    backbone=dict(type='DenseNet', arch='121'),
    neck=dict(type='GlobalAveragePooling'),
    head=dict(
        type='LinearClsHead',
        num_classes=3,
        in_channels=1024,
        loss=dict(type='CrossEntropyLoss', loss_weight=1.0),
    ))
```
```
# densenet121_1×b64_COVIDx.py
_base_ = [
    '../_base_/models/densenet/densenet121_COVIDx.py',
    '../_base_/datasets/COVIDx_bs64.py',
    '../_base_/schedules/imagenet_bs256.py',
    '../_base_/default_runtime.py',
]
runner = dict(type='EpochBasedRunner', max_epochs=90)
```
```
# COVIDx.py
import mmcv
import numpy as np

from .builder import DATASETS
from .base_dataset import BaseDataset


@DATASETS.register_module()
class COVIDx(BaseDataset):

    def load_annotations(self):
        assert isinstance(self.ann_file, str)

        data_infos = []
        with open(self.ann_file) as f:
            samples = [x.strip().split(' ') for x in f.readlines()]
            for filename, gt_label in samples:
                info = {'img_prefix': self.data_prefix}
                info['img_info'] = {'filename': filename}
                info['gt_label'] = np.array(gt_label, dtype=np.int64)
                data_infos.append(info)
            return data_infos
```
```
# __init__.py
from .base_dataset import BaseDataset
from .builder import (DATASETS, PIPELINES, SAMPLERS, build_dataloader,
                      build_dataset, build_sampler)
from .cifar import CIFAR10, CIFAR100
from .cub import CUB
from .custom import CustomDataset
from .dataset_wrappers import (ClassBalancedDataset, ConcatDataset,
                               KFoldDataset, RepeatDataset)
from .imagenet import ImageNet
from .imagenet21k import ImageNet21k
from .mnist import MNIST, FashionMNIST
from .multi_label import MultiLabelDataset
from .samplers import DistributedSampler, RepeatAugSampler
from .stanford_cars import StanfordCars
from .voc import VOC
from .COVIDx import COVIDx
__all__ = [
    'BaseDataset', 'ImageNet', 'CIFAR10', 'CIFAR100', 'MNIST', 'FashionMNIST',
    'VOC', 'MultiLabelDataset', 'build_dataloader', 'build_dataset',
    'DistributedSampler', 'ConcatDataset', 'RepeatDataset',
    'ClassBalancedDataset', 'DATASETS', 'PIPELINES', 'ImageNet21k', 'SAMPLERS',
    'build_sampler', 'RepeatAugSampler', 'KFoldDataset', 'CUB',
    'CustomDataset', 'StanfordCars',  'COVIDx'
]
```

**Comment by yingfhu** [comment] 2022-11-10 09:35
The config looks good to me, it seems like

**Comment by yingfhu** [comment] 2022-11-10 09:35
The config look

**Comment by yingfhu** [comment] 2022-11-10 09:41
The config looks good to me, it might be caused by this line
```
for filename, gt_label in samples:
```
I suggest that you should check your annotation txt first

**Comment by Xglbrilliant** [comment] 2022-11-10 09:54
This is my annotation txt：
![image](https://user-images.githubusercontent.com/95476150/201059008-afc3c1c2-ab62-44b1-abfd-67c205c5073b.png)

**Comment by yingfhu** [comment] 2022-11-10 09:58
x.strip().split(' ') will spilt line ` Viral ....` into 3 pieces, you should handle this case carefully.

**Comment by Xglbrilliant** [comment] 2022-11-10 10:13
> x.strip().split(' ') will spilt line ` Viral ....` into 3 pieces, you should handle this case carefully.

You are absolutely right, indeed! Finally, can I ask if you have a good solution to this problem? Thank you very much for your answer.

**Comment by yingfhu** [comment] 2022-11-10 11:33
For sure, you can use x.strip().rsplit(' ', 1).
Since the problem is solved, I will close this issue, btw, please try the branch 1.x, we will switch to 1.x in the next year.

**Closed by yingfhu** 2022-11-10 11:33 UTC
