### ISSUE TITLE
Can I set different learning rates for different layers of the model?

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmclassification#86] opened 2020-11-13 05:12 UTC
for example,
optimizer:
resnet50.layer1.parameters(), lr＝lr/10
resnet50.layer2.parameters(), lr＝lr/5
resnet50.layer3.parameters(), lr＝lr/2
resnet50.layer4.parameters(), lr＝lr

Could you tell me how can I achieve it in mmdet？
thank you！

**Comment by mzr1996** [comment] 2021-09-18 09:51
Duplicate of #46.

**Closed by mzr1996** 2021-09-18 09:51 UTC
