### ISSUE TITLE
Which version of the Imagenet dataset is used for training？？？

### ISSUE THREAD

**Issue by huoguangdiandian** [open-mmlab/mmclassification#928] opened 2022-07-26 02:50 UTC
hi，II would like to ask which version of the imagenet dataset was used to train resnet50. When comparing the training logs, it was found that the number of iterations of each epoch was different. such as mine is 40000 and yours is 5000

**Comment by Ezra-Yu** [comment] 2022-07-26 02:55
We use 8 GPUs when training. The '8×128' in config names means 8 GPUs and 128 samples for each GPU.

**Comment by huoguangdiandian** [comment] 2022-07-26 05:37
@Ezra-Yu thanks for your reply. I can not find '8x128'in config files, and I  get the top1 is  74.386% of using the '8xbs32' and That's two percent less than the model you provided

**Comment by Ezra-Yu** [comment] 2022-07-26 05:45
'8x128' is just an example to illustrate the experiment's configuration. '8xbs32'  means using 8 GPU and each GPU using `batchsize` of 32. Do you use only one GPU to get the 74.386% result? In this way, the 'lr' should be modified correspondingly. Due to the batchsize being charged, the final result may be different.

**Comment by huoguangdiandian** [comment] 2022-07-26 06:03
@Ezra-Yu thank you, I use only one GPU and don not modify Parameters include 'lr'. I'll try again after modifying the corresponding parameters

**Comment by Ezra-Yu** [comment] 2022-07-26 06:11
Maybe, you can try to use [gradient-accumulation](https://mmclassification.readthedocs.io/en/latest/tutorials/schedule.html#gradient-accumulation). 

Even if you modify the LR and use the gradient-accumulation, I am not sure you can reproduce the result of the '8xbs32'. I have not done such experiments and I also don't recommend running such a large dataset on a single GPU.

I will close this issue later.

**Comment by huoguangdiandian** [comment] 2022-07-26 07:23
@Ezra-Yu the model size of you provided is 97.78M and my model size is 195.38M, Why the difference?

**Comment by Ezra-Yu** [comment] 2022-07-26 07:29
> @Ezra-Yu the model size of you provided is 97.78M and my model size is 195.38M, Why the difference?

There are 'optimizer' and other things in your checkpoint, which are useful when resuming. All the weights provided by mmcls are got from the script of [`./tools/convert_models/publish_model.py`](https://github.com/open-mmlab/mmclassification/blob/master/tools/convert_models/publish_model.py), which will remove other information in the weight.

**Comment by huoguangdiandian** [comment] 2022-07-26 08:00
thanks for your reply,!! My model size did go down after run the script, thank you very much

**Closed** 2022-08-08 02:30 UTC
Labels: help wanted
